/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as IndexLmsScreenRouteImport } from './routes/index/LmsScreen'

const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLmsScreenRoute = IndexLmsScreenRouteImport.update({
  id: '/index/LmsScreen',
  path: '/index/LmsScreen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/index/LmsScreen': typeof IndexLmsScreenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/index/LmsScreen': typeof IndexLmsScreenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/index/LmsScreen': typeof IndexLmsScreenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/index/LmsScreen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/index/LmsScreen'
  id: '__root__' | '/' | '/index/LmsScreen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  IndexLmsScreenRoute: typeof IndexLmsScreenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/LmsScreen': {
      id: '/index/LmsScreen'
      path: '/index/LmsScreen'
      fullPath: '/index/LmsScreen'
      preLoaderRoute: typeof IndexLmsScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  IndexLmsScreenRoute: IndexLmsScreenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
