/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index/route'
import { Route as IndexLmsScreenImport } from './routes/index/LmsScreen'

// Create/Update Routes

const IndexRouteRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IndexLmsScreenRoute = IndexLmsScreenImport.update({
  id: '/index/LmsScreen',
  path: '/index/LmsScreen',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/index/LmsScreen': {
      id: '/index/LmsScreen'
      path: '/index/LmsScreen'
      fullPath: '/index/LmsScreen'
      preLoaderRoute: typeof IndexLmsScreenImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/index/LmsScreen': typeof IndexLmsScreenRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/index/LmsScreen': typeof IndexLmsScreenRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRouteRoute
  '/index/LmsScreen': typeof IndexLmsScreenRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/index/LmsScreen'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/index/LmsScreen'
  id: '__root__' | '/' | '/index/LmsScreen'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  IndexLmsScreenRoute: typeof IndexLmsScreenRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  IndexLmsScreenRoute: IndexLmsScreenRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/index/LmsScreen"
      ]
    },
    "/": {
      "filePath": "index/route.tsx"
    },
    "/index/LmsScreen": {
      "filePath": "index/LmsScreen.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
